// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1-ToL4HytqGkPe24RtEe-6b9Iwn_NbF4',
    appId: '1:620848273365:web:abc1885ac0c00af5e20f5c',
    messagingSenderId: '620848273365',
    projectId: 'flutter-ecommerce-app-20260704',
    authDomain: 'flutter-ecommerce-app-20260704.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-app-20260704.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiHEzBMI6xblPsJd0mDpz2mKS3k3IBfhg',
    appId: '1:620848273365:android:a5d0d2c35ab591dbe20f5c',
    messagingSenderId: '620848273365',
    projectId: 'flutter-ecommerce-app-20260704',
    storageBucket: 'flutter-ecommerce-app-20260704.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVKI3cmVnyBfU_UuAWow3T-zcrLXmrs2M',
    appId: '1:620848273365:ios:64c34532bddaff07e20f5c',
    messagingSenderId: '620848273365',
    projectId: 'flutter-ecommerce-app-20260704',
    storageBucket: 'flutter-ecommerce-app-20260704.firebasestorage.app',
    iosBundleId: 'com.example.flutterEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVKI3cmVnyBfU_UuAWow3T-zcrLXmrs2M',
    appId: '1:620848273365:ios:64c34532bddaff07e20f5c',
    messagingSenderId: '620848273365',
    projectId: 'flutter-ecommerce-app-20260704',
    storageBucket: 'flutter-ecommerce-app-20260704.firebasestorage.app',
    iosBundleId: 'com.example.flutterEcommerceApp',
  );
}
